output "ec2_public_ip" {
  description = "Elastic IP. Point Cloudflare A-record crackgate.in here."
  value       = aws_eip.web.public_ip
}

output "ec2_ssh" {
  description = "SSH command to the box"
  value       = "ssh -i ~/.ssh/id_ed25519 ubuntu@${aws_eip.web.public_ip}  # bootstrap creates 'deploy' user; switch with: sudo -iu deploy"
}

output "rds_endpoint" {
  description = "RDS Postgres endpoint (set as RDS_HOST in .env.production)"
  value       = aws_db_instance.main.address
}

output "rds_password_secret_command" {
  description = "Command to retrieve the autogenerated RDS password"
  value       = "aws secretsmanager get-secret-value --region ${var.aws_region} --secret-id ${aws_secretsmanager_secret.env.name} --query SecretString --output text  # after you populate it"
  sensitive   = true
}

output "rds_master_password" {
  description = "Generated RDS master password — use ONCE to build .env.production, then never read again."
  value       = random_password.db.result
  sensitive   = true
}

output "ecr_registry" {
  description = "ECR_REGISTRY env var (set in .env.production AND as GitHub Actions secret)"
  value       = split("/", aws_ecr_repository.web.repository_url)[0]
}

output "ecr_repo_uri" {
  description = "Full ECR repo URI"
  value       = aws_ecr_repository.web.repository_url
}

output "uploads_bucket" {
  description = "S3 bucket for user uploads"
  value       = aws_s3_bucket.uploads.bucket
}

output "backups_bucket" {
  description = "S3 bucket for nightly pg_dump backups"
  value       = aws_s3_bucket.backups.bucket
}

output "secret_id" {
  description = "Secrets Manager secret holding .env.production"
  value       = aws_secretsmanager_secret.env.name
}

output "gha_deploy_role_arn" {
  description = "Set this as the AWS_DEPLOY_ROLE_ARN GitHub Actions secret"
  value       = aws_iam_role.gha_deploy.arn
}

output "next_steps" {
  description = "Hand-off checklist"
  value       = <<-EOT

    ✓ Infra provisioned. Now do these in order:

    1. Build .env.production locally from .env.production.aws.example:
         RDS_HOST          = ${aws_db_instance.main.address}
         ECR_REGISTRY      = ${split("/", aws_ecr_repository.web.repository_url)[0]}
         ECR_REPO          = ${aws_ecr_repository.web.repository_url}
         POSTGRES_PASSWORD = (read once: terraform output -raw rds_master_password)
         BACKUP_BUCKET     = ${aws_s3_bucket.backups.bucket}
         UPLOADS_BUCKET    = ${aws_s3_bucket.uploads.bucket}
         AUTH_SECRET       = $(openssl rand -base64 48)
         GOOGLE_CLIENT_ID/SECRET, RAZORPAY_*, etc.

    2. Upload to Secrets Manager:
         aws secretsmanager put-secret-value --region ${var.aws_region} \\
           --secret-id ${aws_secretsmanager_secret.env.name} \\
           --secret-string file://.env.production

    3. SSH to EC2 (wait ~3 min for cloud-init to finish):
         ssh -i ~/.ssh/id_ed25519 ubuntu@${aws_eip.web.public_ip}
         sudo cloud-init status --wait
         sudo cat /var/log/cloud-init-output.log | tail -50

    4. Add Cloudflare A-record:
         crackgate.in     A    ${aws_eip.web.public_ip}    proxied OFF
         www.crackgate.in A    ${aws_eip.web.public_ip}    proxied OFF
       (proxied must be OFF the first time so Caddy can complete the ACME
        HTTP-01 challenge; turn proxy ON after cert issues.)

    5. Set GitHub Actions secrets/vars (repo Settings → Secrets and variables):
         secret  AWS_DEPLOY_ROLE_ARN = ${aws_iam_role.gha_deploy.arn}
         secret  ECR_REGISTRY        = ${split("/", aws_ecr_repository.web.repository_url)[0]}
         secret  EC2_HOST            = ${aws_eip.web.public_ip}
         secret  EC2_SSH_KEY         = (private key paired with ${aws_key_pair.deploy.key_name})
         secret  SLACK_WEBHOOK_URL   = ...
         vars    NEXT_PUBLIC_*       = (per Dockerfile build args)

    6. Push to main → GitHub Actions builds + deploys.
       First deploy also runs `prisma migrate deploy`.

    7. Smoke test:
         curl -fsS https://${var.domain}/api/healthz
  EOT
}
