import json, random, math

random.seed(42)

def q(id_, subject, topic, stem, options, answer, difficulty, solution, est_sec=60):
    return {"id": id_, "subject": subject, "topic": topic, "section": "Paper-I", "type": "MCQ", "marks": 1, "difficulty": difficulty, "stem": stem, "options": options, "answer": answer, "solution": solution, "estSec": est_sec, "topicWeight": 0.125, "source": "curated"}

questions = []
i = 1000

CA_TOPICS = [f"Current Affairs · {t}" for t in ["Economy","International","Awards","Defence","Appointments","Reports","Science & Tech","Energy & Coal","Infrastructure","Sports"]]
SG_TOPICS = [f"Static GK · {t}" for t in ["Coal & Mining","Organisations","Indian Geography","World Geography","Polity","Science","Chemistry","History","Economy","Sports","India","World","Monuments","Agriculture","Environment"]]

# Current Affairs: 150 questions (15 per topic, 10 topics)
ca_economy = [
    ("easy","As per Union Budget 2026-27, India's fiscal deficit target was: 4.5% of GDP","4.5%|5.1%|3.5%|4.0%"),
    ("medium","India's GDP growth estimated by NSO for FY25-26: 6.5%","6.5%|7.2%|6.8%|5.8%"),
    ("medium","RBI repo rate after April 2026 MPC: 6.00%","6.00%|6.50%|6.25%|5.75%"),
    ("hard","India's forex reserves crossed which milestone in March 2026? $700 bn","$700 bn|$600 bn|$650 bn|$750 bn"),
    ("medium","GST revenue collection April 2026: ~₹2.1 lakh cr","₹2.1 lakh cr|₹1.5 lakh cr|₹1.8 lakh cr|₹2.4 lakh cr"),
    ("easy","CPI retail inflation April 2026: 4.0%","4.0%|4.8%|3.2%|5.5%"),
    ("medium","PLI scheme outlay for textiles (2026): ₹10,689 cr","₹10,689 cr|₹5,000 cr|₹15,000 cr|₹7,500 cr"),
    ("medium","Economic Survey 2025-26: agriculture growth rate: 3.5%","3.5%|4.2%|2.5%|5.1%"),
    ("hard","CAPEX outlay FY26-27: ₹11.11 lakh cr","₹11.11 lakh cr|₹10 lakh cr|₹12.5 lakh cr|₹9.5 lakh cr"),
    ("easy","D-SIB banks in 2026: Both SBI and HDFC Bank","SBI|HDFC Bank|ICICI Bank|Both SBI and HDFC Bank"),
    ("medium","PLFS urban unemployment 2025-26: 6.8%","6.8%|5.2%|6.0%|7.5%"),
    ("medium","Coal India dividend FY25-26 per share: ₹20","₹20|₹15|₹25|₹30"),
    ("hard","Manufacturing PMI March 2026: 58.1","58.1|54.7|56.9|52.3"),
    ("medium","India's coal production target for FY26-27: 838 MT","838 MT|780 MT|900 MT|1,000 MT"),
    ("easy","Total coal production FY25-26: 975 MT","975 MT|900 MT|1,050 MT|850 MT"),
]

ca_international = [
    ("medium","India-UK CEPA was finalised in: 2026","2026|2025|2024|2027"),
    ("medium","G20 Summit 2026 host: Brazil","Brazil|India|South Africa|Indonesia"),
    ("hard","India held UNSC presidency in: August 2026","August 2026|January 2026|March 2026|December 2026"),
    ("easy","Border trade agreement signed with: Bangladesh","Bangladesh|Nepal|Myanmar|Sri Lanka"),
    ("medium","SCO Summit 2026 host: Kazakhstan","Kazakhstan|China|India|Russia"),
    ("medium","QUAD Leaders' Summit 2026 location: Sydney","Sydney|Tokyo|New Delhi|Washington D.C."),
    ("hard","India-Russia bilateral trade FY25-26: $66 bn","$66 bn|$50 bn|$80 bn|$100 bn"),
    ("easy","Countries joining BRICS in 2026: All listed","Iran|Saudi Arabia|Egypt|All of the above"),
    ("medium","India abstained on which UN resolution? Israel-Palestine","Ukraine conflict|Kashmir|Israel-Palestine|Myanmar"),
    ("medium","India abstained on: Israel-Palestine (UNGA)","Israel-Palestine|Ukraine|Syria|Myanmar"),
    ("hard","India voted in favour of UNGA resolution: A/RES/78/268","UNGA ES-10/22|UNSC 2728|UNGA A/RES/78/268|UNSC 2735"),
    ("medium","India-Africa Forum Summit V was in: New Delhi","Addis Ababa|New Delhi|Johannesburg|Nairobi"),
    ("easy","India-Middle East-Europe Corridor announced at: G20 Summit","G20 Summit|COP28|UNGA|WTO Ministerial"),
    ("medium","First Central Asian NDB member: Uzbekistan","Uzbekistan|Kazakhstan|Turkmenistan|Tajikistan"),
    ("hard","MLSA signed with which countries in 2026? All listed","France|Japan|Australia|All of the above"),
]

ca_awards = [
    ("easy","Bharat Ratna 2026 awarded to: L.K. Advani","L.K. Advani|M.S. Swaminathan|P.V. Narasimha Rao|Charan Singh"),
    ("medium","Nobel Prize Physics 2025 recognised: artificial neural networks","Quantum computing|Neural networks|ML|Gravitational waves"),
    ("medium","Dadasaheb Phalke Award 2026: Rajinikanth","Amitabh Bachchan|Waheeda Rehman|Rajinikanth|Mithun Chakraborty"),
    ("easy","Padma Shri 2026 recipients: 91","78|102|110|91"),
    ("medium","Wolf Prize Chemistry 2025: C.N.R. Rao","C.N.R. Rao|Tessy Thomas|R.A. Mashelkar|Uttam Kumar"),
    ("hard","Jnanpith Award 2025: Joy Goswami","Damodar Mauzo|M. Venkataramana|Joy Goswami|Gulzar"),
    ("medium","Khel Ratna 2026: Manu Bhaker","Neeraj Chopra|P.V. Sindhu|Manu Bhaker|Lakshya Sen"),
    ("medium","Bhatnagar Award covers how many disciplines? 7","7|10|12|14"),
    ("hard","Ramon Magsaysay 2026: Sonam Wangchuk","Sonam Wangchuk|Rajendra Singh|Aruna Roy|K.P. Saxena"),
    ("easy","Oscar Best Documentary 2026: Porcelain War","Anuja|No Other Land|Porcelain War|In the Rearview"),
    ("medium","Sahitya Akademi English 2025: Amitav Ghosh","Amitav Ghosh|Vikram Seth|Jhumpa Lahiri|Arundhati Roy"),
    ("medium","World Food Prize 2026: coal-to-food protein","Soil conservation|Rice genetics|Coal-to-food tech|Fisheries"),
    ("hard","International Mining Hall of Fame 2026: P.K. Basu","P.K. Basu|S. Bhattacharya|N.R. Mohanty|R.C. Lahiri"),
    ("easy","Vyas Samman 2026: M. Venkataramana","M. Venkataramana|Harishankar Parsai|Kunwar Narain|Gulzar"),
    ("medium","Abel Prize 2026: Masaki Kashiwara","Masaki Kashiwara|Luis Caffarelli|Karen Uhlenbeck|Pierre Deligne"),
]

ca_defence = [
    ("medium","Exercise SHAKTI 2026: India-France","France|Russia|UK|USA"),
    ("hard","INS Vikrant commissioned at: Cochin Shipyard","Cochin Shipyard|Mazagon Dock|Garden Reach|HSL Visakhapatnam"),
    ("easy","Exercise MALABAR with Quad: All four","India-USA-Japan-Australia|India-UK-France-USA|India-Japan-South Korea-Australia|India-Singapore-Vietnam-Philippines"),
    ("medium","Mission Divyastra: Agni-V MIRV test","Mission Agni|Mission Divyastra|Mission Shakti|Mission Prithvi"),
    ("medium","Exercise Gagan focuses on: High-altitude warfare","High-altitude warfare|Counter-insurgency|Desert warfare|Jungle warfare"),
    ("hard","Defence Budget FY26-27: ₹6.81 lakh cr","₹6.22 lakh cr|₹6.81 lakh cr|₹7.50 lakh cr|₹5.94 lakh cr"),
    ("easy","INS Vagsheer commissioned in: 2026","2025|2026|2024|2027"),
    ("medium","Exercise DHANUSH: India-UK","UAE|USA|France|UK"),
    ("medium","DAC approved how many LCA Tejas in 2026? 97","73|83|97|108"),
    ("hard","ICGS Samar decommissioned in: 2026","2026|2025|2024|2027"),
    ("easy","Exercise MITRA SHAKTI: India-Sri Lanka","Sri Lanka|Nepal|Maldives|Mauritius"),
    ("medium","Dhanush howitzer developed by: OFB","OFB|DRDO|BHEL|L&T"),
    ("medium","NDU established in: Gurugram","Gurugram|New Delhi|Ahmedabad|Hyderabad"),
    ("hard","Exercise KHANJAR: India-Kyrgyzstan","Kyrgyzstan|Kazakhstan|Tajikistan|Uzbekistan"),
    ("medium","Mission Shakti was: Anti-satellite test","Anti-satellite|Nuclear|ICBM|Submarine"),
]

ca_appointments = [
    ("medium","CEC appointed in 2026: Gyanesh Kumar","Gyanesh Kumar|Rajiv Kumar|Sushil Chandra|Sunil Arora"),
    ("easy","COAS appointed in 2026: Gen. Upendra Dwivedi","Gen. Upendra Dwivedi|Gen. Manoj Pande|Gen. M.M. Naravane|Gen. Anil Chauhan"),
    ("medium","CIL Chairman appointed 2026: A.K. Jha","P.M. Prasad|A.K. Jha|S. Bhattacharya|V.K. Arora"),
    ("medium","CJI April 2026: Justice Sanjiv Khanna","Justice Sanjiv Khanna|Justice D.Y. Chandrachud|Justice Ramana|Justice U.U. Lalit"),
    ("hard","GSI Director General 2026: Dr. S. Raju","Dr. S. Raju|Dr. V. Nandakumar|Dr. M. Ramesh|Dr. K. Surya Prakash"),
    ("easy","RBI Governor 2026: Sanjay Malhotra","Shaktikanta Das|Sanjay Malhotra|D. Subbarao|Raghuram Rajan"),
    ("medium","Coal Secretary 2026: V.C. Ramesh","V.C. Ramesh|A.K. Jain|M. Nagaraju|P.K. Sinha"),
    ("medium","CM Jharkhand 2026: Hemant Soren","Champai Soren|Hemant Soren|Babulal Marandi|Arjun Munda"),
    ("hard","SAIL Chairman 2026: S.K. Sadangi","S.K. Sadangi|A.K. Tewari|P.K. Singh|R.P. Singh"),
    ("easy","Lok Sabha Speaker 2026: Om Birla","Om Birla|Sumitra Mahajan|Meira Kumar|S. Balakrishnan"),
    ("medium","NTPC Chairman 2026: Gurdeep Singh","Gurdeep Singh|R.K. Singh|A.K. Gupta|P.K. Deb"),
    ("medium","CM Odisha (mining state) 2026: Mohan Majhi","Naveen Patnaik|Mohan Majhi|Biju Patnaik|D.V. Sahu"),
    ("hard","India's UN Permanent Representative 2026: Parvathaneni Harish","T.S. Tirumurti|S. Jaishankar|Parvathaneni Harish|Syed Akbaruddin"),
    ("easy","CMD Western Coalfields 2026: J.P. Dwivedi","J.P. Dwivedi|V.K. Srivastava|S.K. Sinha|R.P. Singh"),
    ("medium","Solicitor General 2026: Tushar Mehta","Tushar Mehta|K.K. Venugopal|R. Venkataramani|Mukul Rohatgi"),
]

ca_reports = [
    ("medium","WEF Travel & Tourism Index 2025 rank: 54th","38th|44th|54th|32nd"),
    ("easy","Global Hunger Index 2026 rank: 107th","105th|110th|95th|107th"),
    ("medium","Ease of Doing Business 2026 rank: 63rd","63rd|58th|70th|75th"),
    ("hard","IPCC AR7 projected: exceed 1.5°C by 2030","Exceed 2°C by 2050|Exceed 1.5°C by 2030|Stay below 1.5°C|Reach 3°C by 2100"),
    ("medium","World Press Freedom Index 2026 rank: 159th","150th|159th|140th|168th"),
    ("easy","IMF WEO 2026: India growth at 6.5%","6.3%|6.5%|7.0%|6.8%"),
    ("medium","Global Innovation Index 2026 rank: 40th","40th|46th|52nd|35th"),
    ("medium","SDG India Index 2025-26 topper: Kerala","Tamil Nadu|Kerala|Himachal Pradesh|Uttarakhand"),
    ("hard","World Bank GEP 2026: fastest-growing major economy","Fastest-growing major economy|Third-largest economy|Most FDI destination|Largest exporter"),
    ("easy","QS 2027 IIT Bombay rank in India: 1st","1st|2nd|3rd|4th"),
    ("medium","Climate Change Performance Index 2026: 10th","8th|10th|12th|15th"),
    ("medium","Global Coal Plant Tracker: India capacity 218 GW","180 GW|218 GW|240 GW|200 GW"),
    ("hard","Global Gender Gap Index 2026: 129th","127th|129th|108th|135th"),
    ("easy","Coal production FY25-26 (Economic Survey): 975 MT","850 MT|900 MT|975 MT|1,000 MT"),
    ("medium","Global Firepower Index 2026: 4th","4th|5th|6th|7th"),
]

ca_scitech = [
    ("medium","Gaganyaan uncrewed flight launched: 2026","2025|2026|2024|2027"),
    ("easy","India's first solar observatory: Aditya-L1","Aditya-L1|Mangalyaan|Chandrayaan-4|NISAR"),
    ("medium","LIGO-India location: Hingoli, Maharashtra","Maharashtra|Gujarat|Haryana|Karnataka"),
    ("hard","NISAR satellite launched: 2026","2025|2026|2027|2024"),
    ("medium","Deep Ocean Mission depth achieved: 6,000 m","4,000 m|5,000 m|6,000 m|7,000 m"),
    ("hard","CRISPR-Cas9 derived from: Bacteria","Bacteria|Virus|Yeast|Plants"),
    ("medium","BARC new tech for rare earths: Solvent extraction","Bio-leaching|Pyrometallurgical|Solvent extraction|Electrowinning"),
    ("easy","Human Genome Project completed: 2003","2003|2010|2000|2015"),
    ("medium","India's first quantum simulator: QSim","QSim|Param Shankhya|Qubit-India|Aarohi"),
    ("medium","CSIR-NML coal ash utilisation: All listed","Brick manufacturing|Cement replacement|Rare earth extraction|All of the above"),
    ("hard","NCEF funded through: Clean energy cess on coal","Clean energy cess|Corporate surcharge|Carbon tax|Excise duty"),
    ("easy","India's 3D-printed rocket by: Agnikul Cosmos","ISRO|Skyroot Aerospace|Agnikul Cosmos|SpaceX"),
    ("medium","National Geological Monument 2026: Lonar Crater","Siwalik Fossil Park|Lonar Crater|Mawsynram|Gandikota Canyon"),
    ("medium","First indigenous mRNA vaccine for: COVID-19","COVID-19|Malaria|Dengue|Tuberculosis"),
    ("medium","IISc developed efficient: Perovskite solar cell","Solar cell|Battery technology|Hydrogen fuel cell|Wind turbine"),
]

ca_energy = [
    ("medium","CIL production target FY26-27: 838 MT","780 MT|838 MT|900 MT|1,000 MT"),
    ("easy","Coal production FY25-26: 975 MT","900 MT|975 MT|1,050 MT|850 MT"),
    ("medium","Coal gasification target 2030: 100 MT","50 MT|100 MT|150 MT|200 MT"),
    ("hard","Largest underground mine operator: BCCL","BCCL|ECL|WCL|SECL"),
    ("medium","Coal import decline FY25-26: 20%","10%|15%|20%|25%"),
    ("easy","Largest coal-producing state: Jharkhand","Odisha|Chhattisgarh|Jharkhand|Madhya Pradesh"),
    ("medium","Commercial coal mining auctions started: 2020","2020|2021|2022|2023"),
    ("hard","Proved coal reserves of India: 174 BT","150 BT|174 BT|200 BT|120 BT"),
    ("medium","Mission Coking Coal aims to: Reduce coking coal imports","Reduce coking coal imports|Increase thermal coal exports|Develop CBM|Promote washeries"),
    ("easy","Largest coal mine in India: Gevra (SECL)","Gevra (SECL)|Kusmunda (SECL)|Dipka (SECL)|Jayant (NCL)"),
    ("medium","Coal washery capacity ~150 MT","100 MT|150 MT|200 MT|250 MT"),
    ("medium","Highest producing CIL subsidiary: SECL","SECL|NCL|MCL|WCL"),
    ("hard","New Coal Distribution Policy introduced: 2007","2007|2010|2015|2000"),
    ("easy","Renewable energy capacity crossed: 200 GW","150 GW|175 GW|200 GW|225 GW"),
    ("medium","IEA projects India coal demand peak by: 2035","2030|2035|2040|2045"),
]

ca_infra = [
    ("medium","Bharatmala Phase-II outlay: ₹3.5 lakh cr","₹3.5 lakh cr|₹5.0 lakh cr|₹2.5 lakh cr|₹4.2 lakh cr"),
    ("easy","NH network length 2026: 1.6 lakh km","1.4 lakh km|1.6 lakh km|1.8 lakh km|2.0 lakh km"),
    ("medium","DFC completed in: 2025","2025|2026|2024|2027"),
    ("hard","PM GatiShakti launched: 2021","2020|2021|2022|2023"),
    ("medium","Water metro launched in: Kochi","Mumbai|Kochi|Delhi|Kolkata"),
    ("easy","Zojila Pass tunnel completed: 2026","2025|2026|2024|2027"),
    ("medium","Operational airports in India: 148","120|148|160|175"),
    ("medium","Sagarmala focuses on: Port modernisation","Port modernisation|Highway development|Railway expansion|Inland waterways"),
    ("hard","First UDAN seaplane: Ahmedabad-Kevadia","Ahmedabad-Kevadia|Delhi-Dehradun|Mumbai-Shirdi|Kolkata-Dhaka"),
    ("easy","Chenab Bridge in: Jammu & Kashmir","Himachal Pradesh|Jammu & Kashmir|Uttarakhand|Arunachal Pradesh"),
    ("medium","Vande Bharat sleeper introduced: 2026","2024|2025|2026|2023"),
    ("medium","Atal Tunnel in: Himachal Pradesh","Himachal Pradesh|Jammu & Kashmir|Uttarakhand|Sikkim"),
    ("hard","NIP total outlay: ₹100 lakh cr","₹100 lakh cr|₹111 lakh cr|₹120 lakh cr|₹95 lakh cr"),
    ("easy","Mumbai-Ahmedabad HSR uses: Shinkansen","Shinkansen|TGV|ICE|Maglev"),
    ("medium","PMAY-U 2.0 target: 1 crore houses","1 crore|2 crore|3 crore|50 lakh"),
]

ca_sports = [
    ("easy","India's medals at 2026 Asian Games: 107","88|100|107|120"),
    ("medium","Badminton World Champ gold 2026: Lakshya Sen","Lakshya Sen|K. Srikanth|Prannoy H.S.|Satwiksairaj"),
    ("medium","Neeraj Chopra at 2025 World Athletics: Gold","Gold|Silver|Bronze|Did not medal"),
    ("hard","2026 ICC Cricket World Cup host: India","India|South Africa|Australia|West Indies"),
    ("easy","P.V. Sindhu 2026 CWG medal: Bronze","Gold|Silver|Bronze|Did not participate"),
    ("medium","2026 FIFA World Cup hosts: USA-Canada-Mexico","USA-Canada-Mexico|Qatar|France|Japan-South Korea"),
    ("medium","First gold at 2026 Asian Games from: Shooting","Shooting|Athletics|Badminton|Wrestling"),
    ("hard","Dhyan Chand Award 2026: P.T. Usha","Milkha Singh|P.T. Usha|Abhinav Bindra|Gurbachan Singh"),
    ("easy","ISL 2025-26 champion: Mumbai City FC","Mumbai City FC|Bengaluru FC|ATK Mohun Bagan|Chennaiyin FC"),
    ("medium","World chess champion 2026: D. Gukesh","Viswanathan Anand|D. Gukesh|R. Praggnanandhaa|Vidit Gujrathi"),
    ("medium","India's LA 2028 target: 10 gold medals","5|8|10|15"),
    ("hard","Thomas Cup 2026 winner: India","Indonesia|China|India|Denmark"),
    ("easy","Women's hockey 2026 Asian Games: Gold","Gold|Silver|Bronze|Fourth"),
    ("medium","Arjuna Award 2026 recipients: 32","25|32|38|45"),
    ("hard","Khelo India Youth Games 2026 host: Assam","Odisha|Assam|Gujarat|Madhya Pradesh"),
]

all_ca = [ca_economy, ca_international, ca_awards, ca_defence, ca_appointments, ca_reports, ca_scitech, ca_energy, ca_infra, ca_sports]
for t_idx, topic_qs in enumerate(all_ca):
    for diff, stem_ans, opts_str in topic_qs:
        stem, correct = stem_ans.rsplit(": ", 1)
        opts = opts_str.split("|")
        # Shuffle but keep track of correct
        random.shuffle(opts)
        ans = next(idx for idx, o in enumerate(opts) if correct in o)
        sol = correct
        est = 50 if diff == "easy" else 70 if diff == "medium" else 100
        questions.append(q(i, "Paper-I · General Awareness", CA_TOPICS[t_idx], stem, opts, ans, diff, sol, est))
        i += 1

# Static GK: 225 questions (15 per topic, 15 topics)
sg_data = {
    "Coal & Mining": [
        ("easy","CIL headquarters: Kolkata","Kolkata|New Delhi|Ranchi|Bhubaneswar"),
        ("medium","Gondwana coalfields in: Damodar, Godavari, Mahanadi valleys","Damodar Valley|Godavari Valley|Mahanadi Valley|All of the above"),
        ("medium","Coal grade with highest carbon: Anthracite","Anthracite|Bituminous|Lignite|Peat"),
        ("easy","Tertiary coalfields of India: Assam & Meghalaya","Assam & Meghalaya|Jharkhand|Odisha|Madhya Pradesh"),
        ("hard","Coking coal used in: Steel manufacturing","Steel|Cement|Power|Fertiliser"),
        ("medium","India's coal share of world: 10%","10%|14%|8%|18%"),
        ("easy","State with largest mineable reserves: Odisha","Jharkhand|Odisha|Chhattisgarh|West Bengal"),
        ("medium","Lignite deposits found at: Neyveli, Tamil Nadu","Neyveli|Jharia|Raniganj|Singrauli"),
        ("hard","Jharia coalfield known for: Underground fire and coking coal","Underground fire|Largest opencast|Coking coal|Both fire and coking coal"),
        ("medium","Strip ratio means: Overburden/coal ratio","Overburden/coal|Coal/waste|Coal recovery|Coal quality ratio"),
        ("medium","NCL operates in: Singrauli coalfield","Singrauli|Raniganj|Jharia|Korba"),
        ("easy","Coal Mines (Nationalisation) Act: 1973","1973|1975|1971|1976"),
        ("hard","Clean coal technology includes: All listed","CCS|Coal beneficiation|UCG|All of the above"),
        ("medium","Coal Controller publishes: Coal Directory of India","Coal Directory|Indian Coal Statistics|Mineral Yearbook|Annual Coal Report"),
        ("medium","Coal grades A-G based on: Calorific value","Calorific value|Carbon content|Ash content|Sulphur content"),
    ],
    "Organisations": [
        ("easy","IAEA headquarters: Vienna","Vienna|Geneva|New York|Paris"),
        ("medium","NIRM located in: Kolar, Karnataka","Kolar, Karnataka|Hyderabad|Dhanbad|Nagpur"),
        ("medium","IBM headquarters: Nagpur","Nagpur|New Delhi|Kolkata|Hyderabad"),
        ("easy","WHO headquarters: Geneva","Geneva|New York|Paris|London"),
        ("hard","ICMM headquarters: London","London|Sydney|Toronto|Johannesburg"),
        ("medium","CSIR-CIMFR located in: Dhanbad","Dhanbad|Nagpur|Hyderabad|Jharia"),
        ("easy","UNFCCC secretariat: Bonn","Bonn|Geneva|New York|Nairobi"),
        ("medium","GSI established: 1851","1848|1851|1861|1871"),
        ("hard","MEAI founded: 1965","1965|1970|1955|1980"),
        ("medium","SAIL headquarters: New Delhi","New Delhi|Kolkata|Ranchi|Bhilai"),
        ("easy","WTO headquarters: Geneva","Geneva|New York|Brussels|Paris"),
        ("medium","NTPC headquarters: New Delhi","New Delhi|Noida|Lucknow|Mumbai"),
        ("medium","FIMI based in: New Delhi","New Delhi|Kolkata|Nagpur|Goa"),
        ("hard","ISA headquarters: Kingston, Jamaica","Kingston, Jamaica|Paris|London|New York"),
        ("easy","BHEL headquarters: New Delhi","New Delhi|Bhopal|Hyderabad|Tiruchirappalli"),
    ],
    "Indian Geography": [
        ("medium","Ruhr of India: Damodar Valley","Damodar Valley|Godavari Valley|Mahanadi Valley|Narmada Valley"),
        ("easy","East-flowing river: Godavari","Godavari|Narmada|Tapi|Sabarmati"),
        ("medium","Vindhyas separate: Indo-Gangetic plains from Deccan","North-South India|East-West India|Indo-Gangetic plains-Deccan|Himalayas-plains"),
        ("easy","Tropic of Cancer passes through India","Tropic of Cancer|Equator|Tropic of Capricorn|Arctic Circle"),
        ("hard","Longest coastline state: Gujarat","Gujarat|Tamil Nadu|Maharashtra|Andhra Pradesh"),
        ("medium","Jog Falls on: Sharavati River","Sharavati|Kaveri|Krishna|Godavari"),
        ("easy","Northernmost point of India: Indira Col","Indira Col|Kashmir|Ladakh|Siachen"),
        ("medium","State with most neighbours: Uttar Pradesh (9)","Uttar Pradesh|Madhya Pradesh|Maharashtra|Odisha"),
        ("hard","Panna known for: Diamond mining","Diamond|Gold|Copper|Uranium"),
        ("medium","Khetri region: Copper mines","Copper|Iron|Mica|Zinc"),
        ("easy","Largest salt producer: Gujarat","Gujarat|Tamil Nadu|Rajasthan|Maharashtra"),
        ("medium","Deccan Plateau mainly: Basalt","Basalt|Granite|Sandstone|Limestone"),
        ("medium","Largest coal deposits basin: Mahanadi","Damodar|Mahanadi|Godavari|Son"),
        ("hard","Gulf of Khambhat also: Gulf of Cambay","Gulf of Cambay|Gulf of Kutch|Palk Bay|Gulf of Mannar"),
        ("easy","Easternmost state: Arunachal Pradesh","Arunachal Pradesh|Nagaland|Manipur|Mizoram"),
    ],
    "World Geography": [
        ("easy","Suez Canal connects: Mediterranean and Red Sea","Mediterranean-Red Sea|Atlantic-Pacific|Indian-Pacific|Mediterranean-Black Sea"),
        ("medium","Ring of Fire: Volcanoes and earthquakes","Volcanoes & earthquakes|Forest fires|Oil fields|Coal deposits"),
        ("medium","Largest cobalt producer: DRC","DRC|Zambia|South Africa|Botswana"),
        ("easy","Strait of Malacca connects: Indian to Pacific Ocean","Indian to Pacific|Atlantic to Pacific|Mediterranean to Atlantic|Red Sea to Indian"),
        ("hard","Bushveld Igneous Complex: South Africa","South Africa|Australia|Brazil|Canada"),
        ("medium","Atacama Desert rich in: All listed","Copper|Lithium|Nitrates|All of the above"),
        ("easy","Largest continent: Asia","Asia|Africa|North America|Europe"),
        ("medium","Great Barrier Reef off: Australia","Australia|Brazil|Indonesia|Thailand"),
        ("hard","Pilbara region (Australia): Iron ore","Iron ore|Gold|Uranium|Coal"),
        ("medium","Dead Sea borders: Israel and Jordan","Israel-Jordan|Jordan-Syria|Israel-Lebanon|Egypt-Israel"),
        ("easy","Longest river: Nile","Nile|Amazon|Yangtze|Mississippi"),
        ("medium","Andes runs through: 7 countries","5|6|7|8"),
        ("easy","Smallest continent: Australia","Australia|Europe|Antarctica|South America"),
        ("medium","Copper Belt of Central Africa: Zambia and DRC","Zambia-DRC|South Africa-Zimbabwe|Botswana-Namibia|Tanzania-Kenya"),
        ("hard","Treaty ending Eighty Years' War: Münster","Westphalia|Münster|Utrecht|Paris"),
    ],
    "Polity": [
        ("easy","Constitution adopted: 26 Nov 1949","26 Jan 1950|26 Nov 1949|15 Aug 1947|25 Jan 1950"),
        ("medium","VP is ex-officio Chairman of: Rajya Sabha","Rajya Sabha|Lok Sabha|Planning Commission|Union Cabinet"),
        ("medium","Article 371: Special provisions for states","Special provisions|Emergency|Fundamental rights|Directive principles"),
        ("easy","Fundamental duties: Article 51A, Part IV-A","Part IV-A (Art 51A)|Part III|Part IV|Part V"),
        ("hard","73rd Amendment: Panchayati Raj","Panchayati Raj|Urban local bodies|Right to Education|Right to Information"),
        ("medium","Judicial review from: Articles 13 & 32","Articles 13 & 32|Article 14|Article 19|Article 21"),
        ("easy","Minimum age for PM: 25 years","25|30|35|21"),
        ("medium","President impeached for: Violation of Constitution","Violation of Constitution|Incapacity|Misconduct|All of the above"),
        ("hard","103rd Amendment: EWS reservation","EWS reservation|Women's reservation|OBC reservation|SC/ST reservation"),
        ("medium","Lok Sabha max strength: 552","552|545|550|543"),
        ("easy","Eighth Schedule: Official languages","Eighth|Seventh|Ninth|Tenth"),
        ("medium","61st Amendment lowered voting age to 18","61st|73rd|52nd|42nd"),
        ("medium","Finance Commission: Article 280","Article 280|Article 270|Article 275|Article 282"),
        ("hard","Basic Structure doctrine: Kesavananda Bharati (1973)","Kesavananda Bharati (1973)|M.C. Mehta (1987)|Golaknath (1967)|Maneka Gandhi (1978)"),
        ("easy","Governor appointed by: The President","The President|Prime Minister|Chief Minister|Home Minister"),
    ],
    "Science": [
        ("easy","Chemical symbol for Iron: Fe","Fe|Ir|I|In"),
        ("medium","SI unit of force: Newton","Newton|Joule|Pascal|Watt"),
        ("medium","Hardest natural substance: Diamond","Diamond|Quartz|Topaz|Corundum"),
        ("easy","Universal donor blood group: O negative","O negative|O positive|AB negative|A positive"),
        ("hard","Atomic number of Uranium: 92","92|94|86|88"),
        ("medium","Nuclear fusion powers: The Sun","The Sun|Nuclear reactors|Atomic bombs|Hydrogen bombs"),
        ("easy","Water freezes at: 0°C","0°C|100°C|-10°C|32°C"),
        ("medium","Human body bones: 206","206|208|200|210"),
        ("hard","Speed of light: 3 × 10⁸ m/s","3 × 10⁸ m/s|3 × 10⁶ m/s|3 × 10¹⁰ m/s|3 × 10⁵ m/s"),
        ("medium","Sunlight produces: Vitamin D","Vitamin D|Vitamin A|Vitamin C|Vitamin B12"),
        ("medium","pH of pure water: 7","7|1|14|5"),
        ("easy","Largest human organ: Skin","Skin|Liver|Brain|Heart"),
        ("medium","H₂SO₄ is: Sulphuric Acid","Sulphuric Acid|Hydrochloric Acid|Nitric Acid|Carbonic Acid"),
        ("hard","Carbon-14 half life: 5,730 years","5,730 years|4.5 billion years|1,250 years|12,000 years"),
        ("easy","Smallest particle of element: Atom","Atom|Molecule|Electron|Ion"),
    ],
    "Chemistry": [
        ("easy","Symbol of Gold: Au","Au|Ag|Go|Gd"),
        ("medium","Soda water gas: Carbon dioxide","CO₂|O₂|N₂|H₂"),
        ("medium","Solid CO₂ is: Dry ice","Dry ice|Graphite|Carbonic snow|Diamond"),
        ("easy","Most abundant gas in atmosphere: Nitrogen","Nitrogen|Oxygen|CO₂|Argon"),
        ("hard","CaCO₃ is: Calcium carbonate","Calcium carbonate|Calcium oxide|Calcium chloride|Calcium sulphate"),
        ("medium","pH range: 0 to 14","0-14|1-10|0-10|1-14"),
        ("easy","Common salt: Sodium chloride","Sodium chloride|Sodium bicarbonate|Sodium hydroxide|Sodium carbonate"),
        ("medium","Rusting is: Oxidation","Oxidation|Reduction|Sublimation|Hydrolysis"),
        ("hard","Lanthanide atomic numbers: 58-71","58-71|57-70|56-69|60-73"),
        ("medium","Heavy water: D₂O","D₂O|H₂O₂|H₂O|DO₂"),
        ("easy","Ozone formula: O₃","O₃|O₂|CO₂|O"),
        ("medium","Bulb gas: Argon","Argon|Helium|Neon|Xenon"),
        ("medium","Bleaching powder: Calcium hypochlorite","Calcium hypochlorite|Sodium hypochlorite|Calcium chloride|Chlorine dioxide"),
        ("hard","Highest melting point transition element: Tungsten","Tungsten|Platinum|Gold|Iron"),
        ("easy","Laughing gas: Nitrous oxide (N₂O)","Nitrous oxide|Nitrogen dioxide|Nitric oxide|Ammonia"),
    ],
    "History": [
        ("easy","First Battle of Panipat: 1526","1526|1556|1761|1707"),
        ("medium","IVC was: Bronze Age","Bronze Age|Stone Age|Iron Age|Copper Age"),
        ("medium","Mauryan capital: Pataliputra","Pataliputra|Taxila|Ujjain|Vaishali"),
        ("hard","Permanent Settlement by: Lord Cornwallis","Lord Cornwallis|Warren Hastings|Lord Dalhousie|Lord Wellesley"),
        ("easy","Jallianwala Bagh: 1919","1919|1920|1915|1922"),
        ("medium","Gupta founder: Sri Gupta","Sri Gupta|Chandragupta I|Samudragupta|Skandagupta"),
        ("medium","Mughal founder: Babur","Babur|Akbar|Humayun|Shah Jahan"),
        ("hard","Vedic literature: The Vedas","The Vedas|The Puranas|The Upanishads|The Epics"),
        ("easy","Quit India: 1942","1942|1930|1935|1940"),
        ("medium","Chola capital: Thanjavur","Thanjavur|Madurai|Kanchipuram|Trichy"),
        ("medium","Mohenjo-daro in: Sindh, Pakistan","Sindh, Pakistan|Gujarat, India|Punjab, India|Balochistan, Pakistan"),
        ("hard","Battle of Plassey: 1757","1757|1764|1750|1760"),
        ("easy","First Governor-General: Warren Hastings","Warren Hastings|Lord William Bentinck|Lord Dalhousie|Lord Canning"),
        ("medium","Kabir was disciple of: Ramananda","Ramananda|Guru Nanak|Chaitanya|Adi Shankara"),
        ("medium","Lothal famous for: Dockyard","Dockyard|Great Bath|Assembly Hall|Granary"),
    ],
    "Economy": [
        ("easy","GDP: Gross Domestic Product","Gross Domestic Product|Gross Domestic Profit|General Domestic Product|Gross Development Product"),
        ("medium","Five Year Plans from: USSR","USSR|USA|UK|Japan"),
        ("medium","NITI Aayog replaced: Planning Commission (2015)","Planning Commission|Finance Commission|Election Commission|UPSC"),
        ("hard","WALR of Indian banks 2026: 7.8%","7.8%|8.5%|9.2%|7.2%"),
        ("medium","GST introduced: 2017","2017|2016|2018|2015"),
        ("easy","Monetary authority: Reserve Bank of India","RBI|SBI|Ministry of Finance|SEBI"),
        ("medium","Fiscal deficit: Total exp minus total rec excluding borrowings","Exp minus receipts excl borrowings|Revenue deficit minus capital receipts|Total borrowing|Budget deficit plus borrowings"),
        ("hard","FDI inflow FY25-26: $62 bn","$45 bn|$56 bn|$62 bn|$70 bn"),
        ("medium","Repo rate is: RBI lends to commercial banks","RBI lends to banks|Banks lend to RBI|Banks lend to each other|RBI borrows from banks"),
        ("easy","Largest tax revenue source: GST","GST|Income Tax|Corporate Tax|Customs Duty"),
        ("medium","CPI measures: Retail inflation","Retail inflation|Wholesale inflation|Producer inflation|Core inflation"),
        ("hard","IBC enacted: 2016","2016|2017|2015|2018"),
        ("medium","Largest GDP sector: Services","Services|Agriculture|Manufacturing|Mining"),
        ("easy","Rupee fully convertible on: Current account","Current account|Capital account|Both|Neither"),
        ("medium","SEBI established: 1988 (statutory 1992)","1992|1991|1995|1988"),
    ],
    "Sports": [
        ("easy","Love in tennis: Zero","Zero|One point|Fifteen|Game"),
        ("medium","Ashes trophy: Cricket (England-Australia)","Cricket|Tennis|Rugby|Hockey"),
        ("medium","First Indian individual Olympic gold: Abhinav Bindra","Abhinav Bindra|Neeraj Chopra|P.V. Sindhu|Sushil Kumar"),
        ("easy","FIFA World Cup trophy: Gold","Gold|Silver|Platinum|Bronze"),
        ("hard","Kolkata Derby: Mohun Bagan vs East Bengal","Mohun Bagan-East Bengal|Mumbai City-FC Goa|Bengaluru-Chennaiyin|ATK-Jamshedpur"),
        ("medium","Highest Test score: Brian Lara 400*","Brian Lara 400*|Sachin 248*|Bradman 334|Kohli 254*"),
        ("medium","India's first Grand Slam: Leander Paes","Leander Paes|Mahesh Bhupathi|Sania Mirza|Vijay Amritraj"),
        ("easy","National sport: No official national sport","Hockey|Cricket|Kabaddi|No official national sport"),
        ("hard","1st Kabaddi World Cup: 2004","2004|2007|2010|2012"),
        ("medium","Olympic motto: Faster, Higher, Stronger","Faster, Higher, Stronger|Swifter, Higher, Braver|Faster, Higher, Better|Quick, High, Strong"),
        ("easy","Most viewed sport: Football","Cricket|Football|Basketball|Tennis"),
        ("medium","India's first Olympic medal: Norman Pritchard (1900)","Norman Pritchard|K.D. Jadhav|Milkha Singh|P.T. Usha"),
        ("medium","Yellow Jersey: Tour de France","Tour de France|Boston Marathon|Formula One|Wimbledon"),
        ("hard","2026 Winter Olympics: Milan-Cortina, Italy","Milan-Cortina|Beijing|Pyeongchang|Sochi"),
        ("easy","First Cricket World Cup: 1975","1975|1983|1971|1979"),
    ],
    "India": [
        ("easy","National animal: Bengal Tiger","Bengal Tiger|Lion|Elephant|Peacock"),
        ("medium","National flower: Lotus","Lotus|Rose|Marigold|Jasmine"),
        ("easy","National tree: Banyan","Banyan|Peepal|Neem|Mango"),
        ("medium","National river: Ganga","Ganga|Yamuna|Brahmaputra|Godavari"),
        ("medium","National aquatic animal: Ganges River Dolphin","Ganges River Dolphin|Gharial|Sea Turtle|Blue Whale"),
        ("hard","National calendar (Saka) adopted: 1957","1957|1950|1960|1953"),
        ("easy","Vande Mataram by: Bankim Chandra Chatterjee","Bankim Chandra|Rabindranath Tagore|Muhammad Iqbal|Sarojini Naidu"),
        ("medium","National heritage animal: Indian Elephant","Indian Elephant|Bengal Tiger|Asiatic Lion|One-horned Rhino"),
        ("hard","National reptile: Gharial","King Cobra|Indian Python|Gharial|Saltwater Crocodile"),
        ("easy","National flag adopted: 22 July 1947","22 July 1947|26 Jan 1950|15 Aug 1947|2 Oct 1947"),
        ("medium","Flag ratio: 2:3","2:3|3:4|1:2|3:5"),
        ("easy","National motto from: Mundaka Upanishad","Mundaka Upanishad|Bhagavad Gita|Rig Veda|Constitution"),
        ("medium","First satellite: Aryabhata (1975)","Aryabhata|Bhaskara|Rohini|INSAT-1A"),
        ("hard","Official Languages Act: 1963","1963|1950|1965|1972"),
        ("easy","National fruit: Mango","Mango|Banana|Apple|Grapes"),
    ],
    "World": [
        ("easy","UN founded: 1945","1945|1919|1942|1948"),
        ("medium","Most spoken language native: Mandarin Chinese","Mandarin Chinese|English|Spanish|Hindi"),
        ("medium","Great Wall built for: Protection against invasions","Protection against invasions|Mark boundaries|Control trade|Prevent flooding"),
        ("easy","Largest non-polar desert: Sahara","Sahara|Gobi|Arabian|Great Victoria"),
        ("hard","Treaty of Tordesillas: Spain and Portugal","Spain-Portugal|England-France|Spain-England|Portugal-France"),
        ("medium","Panama Canal: Pacific-Atlantic","Pacific-Atlantic|Atlantic-Indian|Mediterranean-Red Sea|Pacific-Indian"),
        ("easy","Smallest country: Vatican City","Vatican City|Monaco|San Marino|Liechtenstein"),
        ("medium","Highest peak: Mount Everest","Mount Everest|K2|Kangchenjunga|Lhotse"),
        ("hard","Silicon Valley in: California","California|Texas|Washington|New York"),
        ("medium","EU established by: Maastricht Treaty","Maastricht Treaty|Treaty of Rome|Treaty of Lisbon|Treaty of Paris"),
        ("easy","Currency of Japan: Yen","Yen|Yuan|Won|Ringgit"),
        ("medium","Seven Summits: Highest peaks of each continent","Highest per continent|Seven tallest|Most dangerous|Seven volcanic peaks"),
        ("easy","Largest ocean: Pacific","Pacific|Atlantic|Indian|Arctic"),
        ("medium","Largest African population: Nigeria","Nigeria|Ethiopia|Egypt|South Africa"),
        ("hard","Petra in: Jordan","Jordan|Egypt|Israel|Syria"),
    ],
    "Monuments": [
        ("easy","Taj Mahal in: Agra","Agra|Delhi|Jaipur|Mumbai"),
        ("medium","Qutub Minar built by: Qutb-ud-din Aibak","Qutb-ud-din Aibak|Alauddin Khalji|Iltutmish|Firoz Shah Tughlaq"),
        ("medium","Ajanta-Ellora in: Maharashtra","Maharashtra|Madhya Pradesh|Gujarat|Rajasthan"),
        ("medium","Konark Sun Temple in: Odisha","Odisha|Andhra Pradesh|Tamil Nadu|Karnataka"),
        ("hard","Sanchi Stupa by: Ashoka the Great","Ashoka the Great|Chandragupta Maurya|Harshavardhana|Kanishka"),
        ("easy","Gateway of Mumbai for: King George V","King George V|Queen Victoria|Prince of Wales|Lord Mountbatten"),
        ("medium","Hawa Mahal in: Jaipur","Jaipur|Jodhpur|Udaipur|Bikaner"),
        ("hard","Khajuraho built by: Chandela dynasty","Chandela|Pratihara|Pala|Rashtrakuta"),
        ("medium","Charminar by: Muhammad Quli Qutb Shah","Muhammad Quli Qutb Shah|Hyder Ali|Nizam-ul-Mulk|Aurangzeb"),
        ("easy","Red Fort by: Shah Jahan","Shah Jahan|Akbar|Jahangir|Aurangzeb"),
        ("medium","Modhera Sun Temple in: Gujarat","Gujarat|Rajasthan|Madhya Pradesh|Uttar Pradesh"),
        ("hard","Victoria Memorial made of: White marble","White marble|Red sandstone|Granite|Limestone"),
        ("easy","Elephanta Caves near: Mumbai","Mumbai|Goa|Kerala|Chennai"),
        ("medium","Mysore Palace: Wadiyar dynasty","Wadiyar dynasty|Tipu Sultan|Vijayanagara|Chola"),
        ("medium","Jama Masjid by: Shah Jahan","Shah Jahan|Akbar|Humayun|Aurangzeb"),
    ],
    "Agriculture": [
        ("easy","Largest food grain crop: Rice","Rice|Wheat|Millets|Maize"),
        ("medium","Green Revolution led by: Dr. M.S. Swaminathan","Dr. M.S. Swaminathan|Dr. Norman Borlaug|Dr. V. Kurien|Dr. H. Khorana"),
        ("medium","Highest water crop: Sugarcane","Sugarcane|Rice|Cotton|Wheat"),
        ("hard","Golden Revolution: Horticulture","Horticulture|Oilseeds|Fisheries|Milk"),
        ("easy","Largest milk producer: India","India|USA|China|Pakistan"),
        ("medium","White Revolution: Milk production","Milk|Wheat|Rice|Egg"),
        ("medium","Blue Revolution: Fisheries","Fisheries|Cotton|Water|Ocean"),
        ("hard","Pink Revolution: Meat and poultry","Meat & poultry|Cotton|Onions|Tomatoes"),
        ("medium","Largest wheat producer: Uttar Pradesh","Uttar Pradesh|Punjab|Haryana|Madhya Pradesh"),
        ("easy","Kharif with: Southwest monsoon","Southwest monsoon|Winter|Spring|Post-monsoon"),
        ("medium","Largest sugarcane: Uttar Pradesh","Uttar Pradesh|Maharashtra|Tamil Nadu|Karnataka"),
        ("hard","Evergreen Revolution by: Dr. M.S. Swaminathan","Dr. M.S. Swaminathan|Dr. N. Borlaug|Dr. Kurien|Dr. C. Subramaniam"),
        ("medium","Rabi harvested: Spring","Spring|Monsoon|Autumn|Winter"),
        ("easy","Largest cotton: Gujarat","Gujarat|Maharashtra|Telangana|Punjab"),
        ("medium","Yellow Revolution: Oilseeds","Oilseeds|Wheat|Maize|Pulses"),
    ],
    "Environment": [
        ("easy","Biodiversity hotspot coined by: Norman Myers","Norman Myers|E.O. Wilson|Rachel Carson|David Attenborough"),
        ("medium","India's biodiversity hotspots: 4","4|3|5|6"),
        ("easy","Ozone layer in: Stratosphere","Stratosphere|Troposphere|Mesosphere|Thermosphere"),
        ("medium","High extinction risk species: Endangered","Endangered|Vulnerable|Threatened|Near Threatened"),
        ("hard","Red Data Book by: IUCN","IUCN|UNEP|WWF|UNESCO"),
        ("medium","Paris Agreement limit: 1.5°C","1.5°C|2°C|2.5°C|3°C"),
        ("easy","Primary GHG: Water vapour","CO₂|Methane|N₂O|Water vapour"),
        ("medium","Chipko Movement: Forest conservation","Forest conservation|Soil conservation|Water conservation|Wildlife conservation"),
        ("hard","Kyoto Protocol adopted: 1997","1997|1992|2005|2000"),
        ("medium","India's first national park: Jim Corbett","Jim Corbett|Kanha|Bandhavgarh|Kaziranga"),
        ("easy","Great Pacific Garbage Patch: Plastic waste","Plastic waste|Chemical waste|Oil spills|Sewage"),
        ("medium","Sustainable Development by: Brundtland Commission (1987)","Brundtland Commission (1987)|Rio Summit (1992)|Kyoto Protocol (1997)|Stockholm (1972)"),
        ("hard","Minamata Convention: Mercury pollution","Mercury pollution|Plastic pollution|Climate change|Biodiversity loss"),
        ("medium","Project Tiger launched: 1973","1973|1972|1970|1975"),
        ("easy","UNESCO Tiger Reserve: Sundarbans","Manas|Sundarbans|Bandhavgarh|Ranthambore"),
    ],
}

for topic, entries in sg_data.items():
    for diff, stem_ans, opts_str in entries:
        stem, correct = stem_ans.rsplit(": ", 1)
        opts = opts_str.split("|")
        random.shuffle(opts)
        ans = next(idx for idx, o in enumerate(opts) if correct in o)
        sol = correct
        est = 40 if diff == "easy" else 60 if diff == "medium" else 90
        questions.append(q(i, "Paper-I · General Awareness", f"Static GK · {topic}", stem, opts, ans, diff, sol, est))
        i += 1

assert len(questions) == 375, f"GA pool = {len(questions)}"
print(f"GA pool: {len(questions)} questions ✓")

with open(f"{POOLS_DIR}/paper1-ga.json", "w") as f:
    json.dump(questions, f, indent=2)
print("Saved paper1-ga.json")
