import { redirect } from "next/navigation";
import { auth } from "@/lib/auth";
import QRCode from "qrcode";
import UpiClaimForm from "./form";
import { db } from "@/lib/db";

export const dynamic = "force-dynamic";

const PLANS = {
  pro:     { amountRupees: 499, label: "Pro",     months: 18 },
  premium: { amountRupees: 899, label: "Premium", months: 18 },
} as const;

type Plan = keyof typeof PLANS;

export default async function PayUpiPage({
  searchParams,
}: {
  searchParams: Promise<{ plan?: string }>;
}) {
  const sp = await searchParams;
  const planKey: Plan = sp.plan === "premium" ? "premium" : "pro";
  const cfg = PLANS[planKey];

  const session = await auth();
  if (!session?.user?.id) {
    redirect(`/login?next=/pay/upi?plan=${planKey}`);
  }

  const vpa = process.env.NEXT_PUBLIC_UPI_VPA || "";
  const payeeName = process.env.NEXT_PUBLIC_UPI_PAYEE_NAME || "CrackGate";

  // Recent claims by this user for status visibility on the same page.
  const myClaims = await db.upiPayment.findMany({
    where: { userId: session.user.id },
    orderBy: { createdAt: "desc" },
    take: 5,
    select: {
      id: true,
      plan: true,
      amountPaise: true,
      upiTxnRef: true,
      status: true,
      adminNote: true,
      createdAt: true,
    },
  });

  // Build UPI deep-link. tn = transaction note (max ~80 chars, plain ASCII).
  // userId is included so we can sanity-check claims against the payer's note
  // when the bank statement doesn't expose it directly.
  const note = `cg-${planKey}-${session.user.id.slice(0, 8)}`;
  const upiUrl = vpa
    ? `upi://pay?pa=${encodeURIComponent(vpa)}&pn=${encodeURIComponent(
        payeeName,
      )}&am=${cfg.amountRupees}&cu=INR&tn=${encodeURIComponent(note)}`
    : "";

  // Server-render QR as inline SVG (no client JS, no extra request).
  const qrSvg = upiUrl
    ? await QRCode.toString(upiUrl, {
        type: "svg",
        errorCorrectionLevel: "M",
        margin: 1,
        width: 256,
      })
    : "";

  return (
    <div className="max-w-3xl mx-auto px-5 py-12">
      <h1 className="text-3xl font-extrabold">Pay ₹{cfg.amountRupees} via UPI</h1>
      <p className="text-muted mt-2">
        {cfg.label} plan · valid through GATE 2027 cycle ({cfg.months} months).
        Manual verification — your access unlocks within a few hours after we
        confirm the payment.
      </p>

      {!vpa && (
        <div className="card p-5 mt-6 border-warn text-warn-foreground">
          UPI is not configured on the server. Ask the admin to set{" "}
          <code>NEXT_PUBLIC_UPI_VPA</code>.
        </div>
      )}

      {vpa && (
        <div className="grid md:grid-cols-2 gap-6 mt-8">
          <div className="card p-6">
            <h2 className="font-bold text-lg">1 · Scan & pay</h2>

            <div
              className="mt-4 bg-white p-3 rounded-md inline-block"
              // qrSvg is generated by `qrcode` from a fully-controlled string
              // (UPI URL with encoded params) — no user input is interpolated.
              dangerouslySetInnerHTML={{ __html: qrSvg }}
            />

            <div className="mt-4 text-sm">
              <div className="text-muted">UPI ID</div>
              <div className="font-mono text-base font-semibold select-all">
                {vpa}
              </div>
            </div>
            <div className="mt-3 text-sm">
              <div className="text-muted">Amount</div>
              <div className="text-2xl font-extrabold">
                ₹{cfg.amountRupees}
              </div>
            </div>
            <div className="mt-3 text-sm">
              <div className="text-muted">Note (auto-filled)</div>
              <div className="font-mono text-xs">{note}</div>
            </div>

            <a
              href={upiUrl}
              className="btn btn-primary mt-5 md:hidden"
            >
              Open in UPI app
            </a>

            <ol className="mt-5 text-xs text-muted list-decimal pl-4 space-y-1">
              <li>Pay the <b>exact</b> amount — ₹{cfg.amountRupees}.</li>
              <li>After it succeeds, copy the <b>UPI Reference Number</b> (UTR / RRN) from the receipt screen.</li>
              <li>Paste it in the form on the right and submit.</li>
            </ol>
          </div>

          <div className="card p-6">
            <h2 className="font-bold text-lg">2 · Submit your UTR</h2>
            <UpiClaimForm plan={planKey} amountRupees={cfg.amountRupees} />
          </div>
        </div>
      )}

      {myClaims.length > 0 && (
        <div className="card p-6 mt-8">
          <h2 className="font-bold text-lg">Your recent claims</h2>
          <div className="mt-3 overflow-x-auto">
            <table className="w-full text-sm">
              <thead className="text-xs text-muted">
                <tr className="text-left">
                  <th className="py-2 pr-3">When</th>
                  <th className="py-2 pr-3">Plan</th>
                  <th className="py-2 pr-3">Amount</th>
                  <th className="py-2 pr-3">UTR</th>
                  <th className="py-2 pr-3">Status</th>
                </tr>
              </thead>
              <tbody>
                {myClaims.map((c) => (
                  <tr key={c.id} className="border-t border-border/60">
                    <td className="py-2 pr-3">
                      {c.createdAt.toISOString().slice(0, 16).replace("T", " ")}
                    </td>
                    <td className="py-2 pr-3">{c.plan}</td>
                    <td className="py-2 pr-3">
                      ₹{Math.round(c.amountPaise / 100)}
                    </td>
                    <td className="py-2 pr-3 font-mono text-xs">
                      {c.upiTxnRef}
                    </td>
                    <td className="py-2 pr-3">
                      <StatusPill status={c.status} note={c.adminNote} />
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </div>
  );
}

function StatusPill({
  status,
  note,
}: {
  status: "pending" | "approved" | "rejected";
  note?: string | null;
}) {
  const cls =
    status === "approved"
      ? "bg-ok/15 text-ok"
      : status === "rejected"
        ? "bg-err/15 text-err"
        : "bg-warn/15 text-warn";
  return (
    <span className="inline-flex flex-col">
      <span className={`px-2 py-0.5 rounded text-xs font-semibold ${cls}`}>
        {status}
      </span>
      {status === "rejected" && note && (
        <span className="text-[10px] text-muted mt-1">{note}</span>
      )}
    </span>
  );
}
