import { redirect } from "next/navigation";
import { auth } from "@/lib/auth";
import QRCode from "qrcode";
import UpiClaimForm from "./form";
import { db } from "@/lib/db";
import { whatsappLink } from "@/lib/contact";

export const dynamic = "force-dynamic";

const PLANS = {
  pro:     { amountRupees: 499, label: "Pro",     months: 18 },
  premium: { amountRupees: 899, label: "Premium", months: 18 },
} as const;

type Plan = keyof typeof PLANS;

export default async function PayUpiPage({
  searchParams,
}: {
  searchParams: Promise<{ plan?: string }>;
}) {
  const sp = await searchParams;
  const planKey: Plan = sp.plan === "premium" ? "premium" : "pro";
  const cfg = PLANS[planKey];

  const session = await auth();
  if (!session?.user?.id) {
    redirect(`/login?next=/pay/upi?plan=${planKey}`);
  }

  const vpa = process.env.NEXT_PUBLIC_UPI_VPA || "";
  const payeeName = process.env.NEXT_PUBLIC_UPI_PAYEE_NAME || "CrackGate";

  // Prefill the claim form from the signed-in user (Google gives name+email;
  // phone is usually empty until they tell us here).
  const [me, myClaims] = await Promise.all([
    db.user.findUnique({
      where: { id: session.user.id },
      select: { name: true, email: true, phone: true },
    }),
    db.upiPayment.findMany({
      where: { userId: session.user.id },
      orderBy: { createdAt: "desc" },
      take: 5,
      select: {
        id: true,
        plan: true,
        amountPaise: true,
        status: true,
        adminNote: true,
        createdAt: true,
      },
    }),
  ]);

  // Build UPI deep-link. tn = transaction note (max ~80 chars, plain ASCII).
  // userId is included so we can sanity-check claims against the payer's note
  // when the bank statement doesn't expose it directly.
  const note = `cg-${planKey}-${session.user.id.slice(0, 8)}`;
  const upiUrl = vpa
    ? `upi://pay?pa=${encodeURIComponent(vpa)}&pn=${encodeURIComponent(
        payeeName,
      )}&am=${cfg.amountRupees}&cu=INR&tn=${encodeURIComponent(note)}`
    : "";

  // Server-render QR as inline SVG (no client JS, no extra request).
  const qrSvg = upiUrl
    ? await QRCode.toString(upiUrl, {
        type: "svg",
        errorCorrectionLevel: "M",
        margin: 1,
        width: 256,
      })
    : "";

  return (
    <div className="max-w-3xl mx-auto px-5 py-12">
      <h1 className="text-3xl font-extrabold">Pay ₹{cfg.amountRupees} via UPI</h1>
      <p className="text-muted mt-2">
        {cfg.label} plan · valid through GATE 2027 cycle ({cfg.months} months).
        Manual verification — your access unlocks within a few hours after we
        confirm the payment.
      </p>

      {!vpa && (
        <div className="card p-5 mt-6 border-warn text-warn-foreground">
          UPI is not configured on the server. Ask the admin to set{" "}
          <code>NEXT_PUBLIC_UPI_VPA</code>.
        </div>
      )}

      {vpa && (
        <div className="grid md:grid-cols-2 gap-6 mt-8">
          <div className="card p-6">
            <h2 className="font-bold text-lg">1 · Scan & pay</h2>

            <div
              className="mt-4 bg-white p-3 rounded-md inline-block"
              // qrSvg is generated by `qrcode` from a fully-controlled string
              // (UPI URL with encoded params) — no user input is interpolated.
              dangerouslySetInnerHTML={{ __html: qrSvg }}
            />

            <div className="mt-4 text-sm">
              <div className="text-muted">UPI ID</div>
              <div className="font-mono text-base font-semibold select-all">
                {vpa}
              </div>
            </div>
            <div className="mt-3 text-sm">
              <div className="text-muted">Amount</div>
              <div className="text-2xl font-extrabold">
                ₹{cfg.amountRupees}
              </div>
            </div>
            <div className="mt-3 text-sm">
              <div className="text-muted">Note (auto-filled)</div>
              <div className="font-mono text-xs">{note}</div>
            </div>

            <a
              href={upiUrl}
              className="btn btn-primary mt-5 md:hidden"
            >
              Open in UPI app
            </a>

            <ol className="mt-5 text-xs text-muted list-decimal pl-4 space-y-1">
              <li>Pay the <b>exact</b> amount — ₹{cfg.amountRupees}.</li>
              <li>Wait for the <b>success</b> screen in your UPI app.</li>
              <li>Fill your name, phone &amp; email on the right and submit.</li>
            </ol>
          </div>

          <div className="card p-6">
            <h2 className="font-bold text-lg">2 · Confirm your payment</h2>
            <UpiClaimForm
              plan={planKey}
              amountRupees={cfg.amountRupees}
              defaultName={me?.name ?? session.user.name ?? ""}
              defaultPhone={me?.phone ?? ""}
              defaultEmail={me?.email ?? session.user.email ?? ""}
            />
          </div>
        </div>
      )}

      {myClaims.length > 0 && (
        <div className="card p-6 mt-8">
          <h2 className="font-bold text-lg">Your recent claims</h2>
          <div className="mt-3 overflow-x-auto">
            <table className="w-full text-sm">
              <thead className="text-xs text-muted">
                <tr className="text-left">
                  <th className="py-2 pr-3">When</th>
                  <th className="py-2 pr-3">Plan</th>
                  <th className="py-2 pr-3">Amount</th>
                  <th className="py-2 pr-3">Status</th>
                </tr>
              </thead>
              <tbody>
                {myClaims.map((c) => (
                  <tr key={c.id} className="border-t border-border/60">
                    <td className="py-2 pr-3">
                      {c.createdAt.toISOString().slice(0, 16).replace("T", " ")}
                    </td>
                    <td className="py-2 pr-3">{c.plan}</td>
                    <td className="py-2 pr-3">
                      ₹{Math.round(c.amountPaise / 100)}
                    </td>
                    <td className="py-2 pr-3">
                      <StatusPill status={c.status} note={c.adminNote} />
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* Trust + support */}
      <div className="mt-8 grid sm:grid-cols-2 gap-4">
        <div className="card p-5">
          <h3 className="font-bold">Why this is safe</h3>
          <ul className="mt-3 space-y-2 text-sm text-muted">
            <li className="flex gap-2">
              <span aria-hidden>⏱️</span>
              <span>Access unlocked within a few hours of payment — usually much faster.</span>
            </li>
            <li className="flex gap-2">
              <span aria-hidden>🔒</span>
              <span>You pay directly through your own UPI app. We never see or store your card or bank details.</span>
            </li>
            <li className="flex gap-2">
              <span aria-hidden>↩️</span>
              <span>
                Covered by our{" "}
                <a href="/refund" className="text-brand hover:underline">
                  refund policy
                </a>
                .
              </span>
            </li>
            <li className="flex gap-2">
              <span aria-hidden>🎓</span>
              <span>Trusted by GATE Mining aspirants preparing for the 2027 cycle.</span>
            </li>
          </ul>
        </div>

        <div className="card p-5 flex flex-col justify-between">
          <div>
            <h3 className="font-bold">Need help?</h3>
            <p className="mt-2 text-sm text-muted">
              Payment stuck, paid the wrong amount, or access not unlocked yet?
              Message us on WhatsApp — we usually reply within minutes.
            </p>
          </div>
          <a
            href={whatsappLink(
              `Hi! I need help with my ${cfg.label} (₹${cfg.amountRupees}) UPI payment.`,
            )}
            target="_blank"
            rel="noopener noreferrer"
            className="btn btn-primary mt-4 w-full"
          >
            💬 Chat with us on WhatsApp
          </a>
        </div>
      </div>
    </div>
  );
}

function StatusPill({
  status,
  note,
}: {
  status: "pending" | "approved" | "rejected";
  note?: string | null;
}) {
  const cls =
    status === "approved"
      ? "bg-ok/15 text-ok"
      : status === "rejected"
        ? "bg-err/15 text-err"
        : "bg-warn/15 text-warn";
  return (
    <span className="inline-flex flex-col">
      <span className={`px-2 py-0.5 rounded text-xs font-semibold ${cls}`}>
        {status}
      </span>
      {status === "rejected" && note && (
        <span className="text-[10px] text-muted mt-1">{note}</span>
      )}
    </span>
  );
}
